### ISSUE TITLE
Malformed or non-canonicalized = expression from short-form function definition

### ISSUE THREAD

**Issue by tkf** [JuliaStaging/JuliaVariables.jl#16]
It would be nice if this works:

```julia
julia> quote
           x = 1
           f(a) = x = 1
       end |> solve
ERROR: #= REPL[43]:3 =#: Malformed or non-canonicalized = expression
```

A bit aside, but what is the best way to do it in MLStyle framework?

**Comment by thautwarm** [comment]
Hi Arakaki-san, this is actually supported!

You should use this code:

```julia
julia>  quote
              x = 1
              f(a) = x = 1
        end |> simplify_ex |> solve

:($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
...
```

By simplifying the expressions to some canonicalized forms, the implementation of `solve` gets really easy.

Everytime you use `solve`, please use `simplify_ex` firstly.

**Comment by tkf** [comment]
Oooh, my bad, you clearly mentioned it in the README. Thanks a lot, Zhao-san!
