### ISSUE TITLE
Rename `solve` to `solve!`?

### ISSUE THREAD

**Issue by tkf** [JuliaStaging/JuliaVariables.jl#17]
It looks like `solve` mutate the input:

```julia
julia> ex = :(x = 1)
       solve(ex)
       ex
:(@global x = 1)
```

If this is intentional, I think it'd be nice to call it `solve!` to be compatible with the usual convention (e.g., `fill!`).  If not, maybe `deepcopy` the input before doing the analysis?

**Comment by thautwarm** [comment]
Oh, thank you for pointing this out.

In the previous version it's pure, but now it's actually impure.

However `solve` is already exported, and used by some libraries, hence currently I feel like to deprecate it.

I promise this improvement in version 0.3.0.

If you want you could make a PR.
