### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStaging/JuliaVariables.jl#20]
Hi again. The current release triggers deprecation warnings from https://github.com/thautwarm/JuliaVariables.jl/blob/5ea76246e6325bb3406c3bb9910c6540fbb19b21/src/JuliaVariables.jl#L9. A new release without warnings would be highly appreciated.

**Comment by thautwarm** [comment]
Thanks for report this

**Comment by thautwarm** [comment]
closed by #21
